apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: sample-app
    version: blue  # Initially points to blue
  ports:
  - port: 80
    targetPort: 3000
