apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-green
  labels:
    app: sample-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
      version: green
  template:
    metadata:
      labels:
        app: sample-app
        version: green
    spec:
      containers:
      - name: sample-app
        image: raheman456/sample-node-app:green
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "green"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
